version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - db
    environment:
      - DATABASE_HOST
      - DATABASE_USERNAME
      - DATABASE_NAME
    ports:
      - 8080:8080
    volumes:
      - .:/api
      - /api/dist
      - /api/node_modules

  db:
    # Uses default port 5432
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    restart: always
